name: list-repo

on:
  push:
    branches:
      - main

jobs:
  list-repo-files:
    name: List files in repository
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: list-dir
        run: ls -laR # Recursively list directory contents

  install-pygount:
    name: install pygount
    runs-on: ubuntu-latest
    steps:
      - name: install-pygount-library
        run: pip install pygount

  count-lines:
    name: count lines
    runs-on: ubuntu-latest
    needs: install-pygount
    steps:
      - name: run-count-lines
        run: pygount --format=summary app.py

