name: list-repo

on:
  push:
    branches:
      - main

jobs:
  list-repo-files:
    name: List files in repository
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: list-dir
        run: ls -laR # Recursively list directory contents

  install-pygount:
    - name: install-pygount
      run: pip install pygount

  count-lines:
    - name: count lines
      needs: install-pygount
      run: pygount  --format=summary app.py

